# Generated by Django 5.0.2 on 2025-03-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('imap_server', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('use_ssl', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=1000)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('folder', models.CharField(max_length=255)),
                ('received_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('interested', 'Interested'), ('meeting_booked', 'Meeting Booked'), ('not_interested', 'Not Interested'), ('spam', 'Spam'), ('out_of_office', 'Out of Office'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('slack_notification_sent', models.BooleanField(default=False)),
                ('webhook_triggered', models.BooleanField(default=False)),
                ('es_indexed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.emailaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['message_id'], name='emails_emai_message_48f464_idx'), models.Index(fields=['category'], name='emails_emai_categor_e46084_idx'), models.Index(fields=['folder'], name='emails_emai_folder_d7ac4b_idx'), models.Index(fields=['received_date'], name='emails_emai_receive_620d6e_idx')],
            },
        ),
    ]
