# Generated by Django 5.0.2 on 2025-03-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AlterModelOptions(
            name='emailaccount',
            options={'verbose_name': 'Email Account', 'verbose_name_plural': 'Email Accounts'},
        ),
        migrations.AddField(
            model_name='email',
            name='reply_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
